{
  # GENERATED by RFC-0005 nix_provisioner from the task contract environment
  # manifest. Committed as a deliverable so build (AIFactory) and verify
  # (TFactory) share one flake.lock and cannot drift. Edit the manifest, not this.
  description = "Factory per-task toolchain (RFC-0005 Tier A)";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/567a49d1913ce81ac6e9582e3553dd90a955875f";
  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
    in {
      devShells.${system}.default = pkgs.mkShell {
        packages = [
          pkgs.kotlin
          pkgs.gradle
          pkgs.jdk21
          # Swift toolchain for the swift-core lane's `swift-unit` gate. nixpkgs
          # `swift` is compiler+driver only; SwiftPM (`swiftpm`) and the
          # corelibs (Dispatch/Foundation/XCTest) are separate derivations and
          # must all be present, per lanes/swift-core/NOTES.md.
          pkgs.swiftPackages.swift
          pkgs.swiftPackages.swiftpm
          pkgs.swiftPackages.Dispatch
          pkgs.swiftPackages.Foundation
          pkgs.swiftPackages.XCTest
        ];
        # SwiftPM compiles and then executes Package.swift, so libdispatch.so
        # et al. must be on the runtime library path before the manifest is
        # even read (lanes/swift-core/NOTES.md). Test discovery uses the
        # explicit LinuxMain.swift + XCTestManifests.swift convention because
        # nixpkgs ships no libIndexStore.so (NixOS/nixpkgs#379859).
        shellHook = ''
          export LD_LIBRARY_PATH="${pkgs.lib.makeLibraryPath [
            pkgs.swiftPackages.Dispatch
            pkgs.swiftPackages.Foundation
            pkgs.swiftPackages.XCTest
          ]}''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
        '';
      };
    };
}
