{
  # GENERATED by RFC-0005 nix_provisioner from the task contract environment
  # manifest. Committed as a deliverable so build (AIFactory) and verify
  # (TFactory) share one flake.lock and cannot drift. Edit the manifest, not this.
  #
  # Provisions BOTH verification lanes' toolchains, because both the kotlin-unit
  # and swift-unit gates resolve this flake's default devShell:
  #   - Kotlin lane (lanes/kotlin-core): jdk21 + gradle + kotlin.
  #   - Swift  lane (lanes/swift-core):  swift + swiftpm + the runtime libraries
  #     (Dispatch/Foundation/XCTest) on LD_LIBRARY_PATH. The nixpkgs `swift`
  #     attribute is compiler+driver only; SwiftPM is a separate derivation and
  #     the manifest is executed at parse time, so libdispatch et al. must be on
  #     the runtime library path before `swift test` runs. See
  #     lanes/swift-core/NOTES.md for the full rationale.
  description = "Factory per-task toolchain (RFC-0005 Tier A)";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/567a49d1913ce81ac6e9582e3553dd90a955875f";
  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
      swiftRuntimeLibs = [
        pkgs.swiftPackages.Dispatch
        pkgs.swiftPackages.Foundation
        pkgs.swiftPackages.XCTest
      ];
    in {
      devShells.${system}.default = pkgs.mkShell {
        packages = [
          # Kotlin lane
          pkgs.kotlin
          pkgs.gradle
          pkgs.jdk21
          # Swift lane (attribute paths match the measured-working set in
          # lanes/swift-core/NOTES.md: swiftPackages.{swift,swiftpm,...})
          pkgs.swiftPackages.swift
          pkgs.swiftPackages.swiftpm
        ] ++ swiftRuntimeLibs;

        # SwiftPM compiles and then executes Package.swift, so the Swift runtime
        # libraries must be resolvable at runtime, not just at link time.
        LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath swiftRuntimeLibs;
      };
    };
}
