{
  # GENERATED by RFC-0005 nix_provisioner from the task contract environment
  # manifest. Committed as a deliverable so build (AIFactory) and verify
  # (TFactory) share one flake.lock and cannot drift. Edit the manifest, not this.
  description = "Factory per-task toolchain (RFC-0005 Tier A)";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/567a49d1913ce81ac6e9582e3553dd90a955875f";
  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
    in {
      devShells.${system}.default = pkgs.mkShell {
        packages = [
          pkgs.kotlin
          pkgs.gradle
          pkgs.jdk21
          # Swift toolchain for the swift-unit gate (lanes/swift-core). The
          # generated manifest omitted it, so `swift test` died with
          # `swift: command not found`. Provisioning per the evaluated recipe in
          # the hub descriptor contracts/languages/swift.yaml: swift is the
          # compiler+driver only, swiftpm supplies `swift test`, and XCTest is
          # the test runtime.
          pkgs.swift
          pkgs.swiftpm
          pkgs.swiftPackages.XCTest
        ];
        # swiftpm's manifest-compile helper and the built test runner link the
        # corelibs at RUN time; without these on LD_LIBRARY_PATH `swift test`
        # dies with "libdispatch.so: cannot open shared object file" before it
        # ever reads Package.swift (per contracts/languages/swift.yaml).
        LD_LIBRARY_PATH = "${pkgs.swiftPackages.Dispatch}/lib:${pkgs.swiftPackages.Foundation}/lib";
      };
    };
}
